development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://iyipdfnvzmyveh:9abca144d59d51b107edb5f63464f7bcacee6ab095167a0972a360457ab2233e@ec2-23-23-142-5.compute-1.amazonaws.com:5432/d2c45oln7vgijn
